# Generated by Django 5.2.8 on 2025-11-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(20, 'ADMIN'), (18, 'DENTIST'), (15, 'TEACHER'), (12, 'STUDENT'), (10, 'PATIENT'), (5, 'GUEST')], default=5),
        ),
    ]
