# Generated by Django 5.2.8 on 2025-11-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='license_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
