# Generated by Django 4.2.27 on 2025-12-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_dentist_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
