# Generated by Django 4.2.27 on 2025-12-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nic',
            field=models.CharField(default='123456789V', max_length=12),
            preserve_default=False,
        ),
    ]
