# Generated by Django 4.2.27 on 2026-02-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentplan',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
