# Generated by Django 5.2.9 on 2026-02-05 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_treatmentplan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=10, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order_index', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RosterWeek',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('week_start_date', models.DateField(unique=True)),
                ('week_end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('LOCKED', 'Locked')], default='DRAFT', max_length=10)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RosterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('assigned_role', models.CharField(choices=[('DENTIST', 'Dentist'), ('SUPPORT', 'Support')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('roster_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='db.rosterweek')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.shift')),
            ],
            options={
                'indexes': [models.Index(fields=['roster_week'], name='db_rosteras_roster__31fe54_idx'), models.Index(fields=['date', 'shift'], name='db_rosteras_date_99d2a3_idx')],
                'unique_together': {('date', 'shift', 'user')},
            },
        ),
    ]
