# Generated by Django 4.2.28 on 2026-02-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_alter_treatmentplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
