# Generated by Django 6.0.5 on 2026-05-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_patientdentalproblem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=10, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order_index', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
