# Generated by Django 5.2.9 on 2026-02-08 10:40

from django.db import migrations

from beyond_health.app.permissions.base import ROLE


def seed_initial_admin(apps, schema_editor):
    User = apps.get_model('db', 'User')

    User.objects.update_or_create(
        username='ke',
        email='keth@demo.com',
        role=ROLE.ADMIN.value,
        mobile_number='0113123456',
        password='demodemo',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20260206_1227'),
    ]

    operations = [
        migrations.RunPython(seed_initial_admin),
    ]
