# Generated by Django 5.2.9 on 2026-02-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20260208_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
