# Generated by Django 4.2.27 on 2026-04-25 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_patient_dob_appointment'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='patient',
        #     name='dob',
        #     field=models.DateField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.dentist'),
        ),
    ]
