# Generated by Django 6.0.5 on 2026-07-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_shift_seeder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(20, 'ADMIN'), (15, 'DENTIST'), (10, 'PATIENT'), (8, 'STAFF'), (5, 'GUEST')], default=5),
        ),
    ]
