# Generated by Django 5.0.4 on 2024-05-05 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.JSONField(default=list)),
                ('details', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('translated_languages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product_type', models.CharField(default='simple', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(null=True)),
                ('min_price', models.FloatField(null=True)),
                ('max_price', models.FloatField(null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('translated_languages', models.JSONField(default=['en'])),
                ('image', models.JSONField(default=dict)),
                ('gallery', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('status', models.CharField(default='publish', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_updated', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='base_products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_string', models.CharField(max_length=255, null=True)),
                ('product_type', models.CharField(default='simple', max_length=20)),
                ('sku', models.CharField(max_length=255)),
                ('title', models.CharField(default='Default Title', max_length=155)),
                ('price', models.FloatField()),
                ('sale_price', models.FloatField(null=True)),
                ('discount', models.FloatField(null=True)),
                ('quantity', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('status', models.CharField(default='publish', max_length=20)),
                ('popular_product', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.baseproduct')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stock', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productCombination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=10)),
                ('translated_languages', models.JSONField(default=list)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('banners', models.JSONField(default=list)),
                ('promotional_sliders', models.JSONField(default=list)),
                ('settings', models.JSONField(default=dict)),
                ('icon', models.CharField(default='default_icon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.type'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.type'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shop_id', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
                ('translated_languages', models.JSONField(default=list)),
                ('slug', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_variants', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_variants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaseProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_product_name', models.CharField(max_length=255)),
                ('variant_name', models.CharField(max_length=255)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.baseproduct')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_product_variants', to='products.variant')),
            ],
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('meta', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('translated_languages', models.JSONField(default=list)),
                ('first_letters', models.CharField(blank=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_variant_options', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_variant_options', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_options', to='products.variant')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='variant_options',
            field=models.ManyToManyField(related_name='products', to='products.variantoption'),
        ),
        migrations.CreateModel(
            name='BaseProductVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_product_name', models.CharField(max_length=255)),
                ('variant_name', models.CharField(max_length=255)),
                ('variant_option_name', models.CharField(max_length=255)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_options', to='products.baseproduct')),
                ('base_product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_product_variants', to='products.baseproductvariant')),
                ('variant_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_product_variant_options', to='products.variantoption')),
            ],
        ),
    ]
