# Generated by Django 5.0.4 on 2024-04-24 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=10)),
                ('translated_languages', models.JSONField(default=list)),
                ('slug', models.CharField(max_length=20)),
                ('banners', models.JSONField(default=list)),
                ('promotional_sliders', models.JSONField(default=list)),
                ('settings', models.JSONField(default=dict)),
                ('icon', models.CharField(default='default_icon', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(default='default-slug', max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(default='publish', max_length=20)),
                ('product_type', models.CharField(default='simple', max_length=20)),
                ('unit', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_taxable', models.BooleanField(default=False)),
                ('popular_product', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('translated_languages', models.JSONField(default=list)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('image', models.JSONField(default=dict)),
                ('gallery', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_updated', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.type')),
            ],
        ),
    ]
