# Generated by Django 5.0.4 on 2024-05-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant_options',
        ),
        migrations.AddField(
            model_name='product',
            name='base_product_variant_options',
            field=models.ManyToManyField(related_name='products', to='products.baseproductvariantoption'),
        ),
    ]
