# Generated by Django 5.0.4 on 2024-05-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseproduct',
            old_name='total_quantity',
            new_name='quantity',
        ),
    ]
