# Generated by Django 5.0.4 on 2024-04-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='translated_languages',
            field=models.JSONField(default=['en']),
        ),
    ]
