# Generated by Django 5.0.4 on 2024-05-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='combination_string',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
