# Generated by Django 5.0.4 on 2024-04-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='translated_languages',
            field=models.JSONField(default=list),
        ),
    ]
