# Generated by Django 5.0.4 on 2024-05-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_total_quantity_baseproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='max_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='min_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
