# Generated by Django 5.0.4 on 2024-05-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_baseproduct_max_price_baseproduct_min_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_price',
        ),
    ]
