# Generated by Django 5.0.4 on 2024-04-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_available_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='status',
            field=models.CharField(default='publish', max_length=20),
        ),
    ]
