# Generated by Django 5.0.4 on 2024-05-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_max_price_remove_product_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='simple', max_length=20),
        ),
    ]
