# Generated by Django 5.0.4 on 2024-04-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_baseproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
