# Generated by Django 5.0.4 on 2024-04-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_baseproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='max_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='min_price',
            field=models.FloatField(null=True),
        ),
    ]
