# Generated by Django 5.0.4 on 2024-04-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_baseproduct_max_price_baseproduct_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
