# Generated by Django 5.0.4 on 2024-04-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_baseproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='title', max_length=155),
            preserve_default=False,
        ),
    ]
